# Generated by Django 5.2 on 2025-04-22 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dateField', models.DateTimeField(verbose_name='Date')),
                ('is_available', models.BooleanField(default=True, verbose_name='Is available')),
                ('technique', models.CharField(max_length=200, verbose_name='Technique used')),
                ('width_cm', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='width (cm)')),
                ('height_cm', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='height (cm)')),
                ('image_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_time', models.DateTimeField(verbose_name='Loan time')),
                ('loan_start', models.DateTimeField(verbose_name='Loan start')),
                ('loan_end', models.DateTimeField(verbose_name='Loan end')),
                ('return_time', models.DateTimeField(verbose_name='Return date')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lainaamo.work')),
            ],
        ),
        migrations.CreateModel(
            name='Join_tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lainaamo.tag')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lainaamo.work')),
            ],
        ),
        migrations.CreateModel(
            name='WorkArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lainaamo.artist')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lainaamo.work')),
            ],
        ),
        migrations.AddField(
            model_name='work',
            name='artists',
            field=models.ManyToManyField(through='lainaamo.WorkArtist', to='lainaamo.artist'),
        ),
    ]
