# Generated by Django 5.2 on 2025-04-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lainaamo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='dateField',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
