# Generated by Django 5.2 on 2025-04-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lainaamo', '0002_alter_work_datefield'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='tags',
            field=models.ManyToManyField(through='lainaamo.Join_tag', to='lainaamo.tag'),
        ),
    ]
