# Generated by Django 5.2 on 2025-04-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lainaamo', '0003_work_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_time',
            field=models.DateField(verbose_name='Loan time'),
        ),
    ]
