# Generated by Django 5.2 on 2025-04-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lainaamo', '0004_alter_loan_loan_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='loan_time',
        ),
        migrations.AlterField(
            model_name='loan',
            name='return_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Return date'),
        ),
        migrations.AlterField(
            model_name='work',
            name='dateField',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
    ]
