# Generated by Django 5.2 on 2025-04-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lainaamo', '0005_remove_loan_loan_time_alter_loan_return_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='tags',
            field=models.ManyToManyField(null=True, through='lainaamo.Join_tag', to='lainaamo.tag'),
        ),
    ]
