# Generated by Django 5.2 on 2025-04-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lainaamo', '0006_alter_work_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='tags',
            field=models.ManyToManyField(through='lainaamo.Join_tag', to='lainaamo.tag'),
        ),
    ]
