# Generated by Django 5.2 on 2025-04-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lainaamo', '0007_alter_work_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='image_url',
            field=models.CharField(max_length=200),
        ),
    ]
