# Generated by Django 5.2 on 2025-04-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lainaamo', '0008_alter_work_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='artwork_images/'),
        ),
    ]
