services:
  dvwa:
    image: vulnerables/web-dvwa
    ports:
      - "8080:80"   # expose DVWA on localhost:8080
    container_name: poc_target
    environment:
      MYSQL_USER: dvwa
      MYSQL_PASSWORD: dvwa
      MYSQL_DATABASE: dvwa
      MYSQL_ROOT_PASSWORD: root
    restart: unless-stopped
    networks:
      - pocnet
networks:
  pocnet:
    driver: bridge